- name: configure nginx server
  hosts: nginx # mention nginx here, it will connect all nginx servers
  become: yes
  tasks:
    - name: install nginx
      ansible_builtin.package:
        name: nginx
        state: present
